//
//  FileUtility.swift
//  Precompilation
//
//  Created by Hoon H. on 2015/01/12.
//  Copyright (c) 2015 Eonil. All rights reserved.
//

import Foundation

public struct FileUtility {
	///	Tries to create a new file with autogenerated name.
	///	Returns URL to the created folder if succeeded.
	///	An error on failure.
	public static func createNewFileInFolder(parentFolder:NSURL) -> Resolution<NSURL> {
		let u2	=	parentFolder
		let	u	=	u2.existingAsDirectoryFile ? u2 : u2.URLByDeletingLastPathComponent!
		assert(u.existingAsDirectoryFile)

		let	PREFIX	=	"New File"
		if let nm = generateUniqueUserFriendlyNameWithPrefixAtParentDirectoryAtURL(u, prefixString: PREFIX) {
			assert(u.URLByAppendingPathComponent("\(nm)", isDirectory: false).existingAsDataFile == false)
			assert(u.URLByAppendingPathComponent("\(nm)", isDirectory: true).existingAsDirectoryFile == false)
			
			let	u1	=	u.URLByAppendingPathComponent("\(nm)", isDirectory: false)
			var	err	=	nil as NSError?
			let	ok	=	NSData().writeToURL(u1, options: NSDataWritingOptions.DataWritingWithoutOverwriting, error: &err)
			if !ok {
				return	Resolution.failure(err!)
			} else {
				return	Resolution.success(u1)
			}
		} else {
			//	No proper name could be made. Sigh...
			let	inf	=	[NSLocalizedDescriptionKey: "There're too many files named \"\(PREFIX)...\". Please erase some before proceeding."]
			let	err	=	NSError(domain: "", code: 0, userInfo: inf)
			return	Resolution.failure(err)
		}
	}
	
	///	Tries to create a new empty directory with autogenerated name.
	///	Returns URL to the created folder if succeeded.
	///	An error on failure.
	public static func createNewFolderInFolder(parentFolder:NSURL) -> Resolution<NSURL> {
		let u2	=	parentFolder
		let	u	=	u2.existingAsDirectoryFile ? u2 : u2.URLByDeletingLastPathComponent!
		assert(u.existingAsDirectoryFile)
		
		let	PREFIX	=	"New Folder"
		if let nm = generateUniqueUserFriendlyNameWithPrefixAtParentDirectoryAtURL(u, prefixString: PREFIX) {
			assert(u.URLByAppendingPathComponent("\(nm)", isDirectory: false).existingAsDataFile == false)
			assert(u.URLByAppendingPathComponent("\(nm)", isDirectory: true).existingAsDirectoryFile == false)
			
			let	u1	=	u.URLByAppendingPathComponent("\(nm)", isDirectory: true)
			var	err	=	nil as NSError?
			let	ok	=	NSFileManager.defaultManager().createDirectoryAtURL(u1, withIntermediateDirectories: true, attributes: nil, error: &err)
			if !ok {
				return	Resolution.failure(err!)
			} else {
				return	Resolution.success(u1)
			}
		} else {
			//	No proper name could be made. Sigh...
			let	inf	=	[NSLocalizedDescriptionKey: "There're too many files named \"\(PREFIX)...\". Please erase some before proceeding."]
			let	err	=	NSError(domain: "", code: 0, userInfo: inf)
			return	Resolution.failure(err)
		}
	}
}



